### ISSUE TITLE
NRE   When picking up a pdf file from iOS 11.0.3

### ISSUE THREAD

**Issue by softsan** [jfversluis/FilePicker-Plugin-for-Xamarin-and-Windows#84] opened 2018-09-27 13:49 UTC
When picking up a pdf file from iOS 11.0.3 it gives following error:

```
Application Specific Information:
*** Terminating app due to uncaught exception 'System.NullReferenceException', reason: 'System.NullReferenceException: Object reference not set to an instance of an object'

Xamarin Exception Stack:
  at Plugin.FilePicker.FilePickerImplementation.DocumentPicker_DidPickDocument (System.Object sender, UIKit.UIDocumentPickedEventArgs e) <0x102606d70 + 0x00074> in <a719614751a746a19785af8e099ab602#daf40facc273510ab77e096a6fd5a912>:0 
  at Plugin.FilePicker.FilePickerImplementation.DocumentPicker_DidPickDocumentAtUrls (System.Object sender, UIKit.UIDocumentPickedAtUrlsEventArgs e) <0x102606c40 + 0x000d7> in <a719614751a746a19785af8e099ab602#daf40facc273510ab77e096a6fd5a912>:0 
  at UIKit.UIDocumentPickerViewController+_UIDocumentPickerDelegate.DidPickDocument (UIKit.UIDocumentPickerViewController controller, Foundation.NSUrl[] urls) <0x101914ba0 + 0x0008b> in <4ab8db046af64ab0ae036378dae8bfd3#daf40facc273510ab77e096a6fd5a912>:0 
  at (wrapper managed-to-native) UIKit.UIApplication.UIApplicationMain(int,string[],intptr,intptr)
  at UIKit.UIApplication.Main (System.String[] args, System.IntPtr principal, System.IntPtr delegate) <0x10190d890 + 0x0002b> in <4ab8db046af64ab0ae036378dae8bfd3#daf40facc273510ab77e096a6fd5a912>:0 
  at UIKit.UIApplication.Main (System.String[] args, System.String principalClassName, System.String delegateClassName) <0x10190d7d0 + 0x000ab> in <4ab8db046af64ab0ae036378dae8bfd3#daf40facc273510ab77e096a6fd5a912>:0 

```
## Expected Behavior
It should pick the file.

## Actual Behavior
It doesn't pick up pdf file.

 

## Specifications

  - NuGet package version:2.0.81-beta
  - Platform(s): iOS

**Comment by vividos** [comment] 2018-10-26 05:08
While testing on iOS I couldn't reproduce this error. Can you test with the latest NuGet package 2.0.106-beta if it still happens? When yes, could you also test with the Sample project in this repository and see on what line exactly the crash happens? Thanks!

**Comment by vividos** [comment] 2018-10-30 19:39
This issue should be fixed with the latest NuGet package. If not, please reopen this issue and comment or add a new issue. Thanks!

**Closed as completed by vividos** 2018-10-30 19:39 UTC
