### ISSUE TITLE
App does not get file permission in Android 10 onwards

### ISSUE THREAD

**Issue by dsvirdiau** [jfversluis/FilePicker-Plugin-for-Xamarin-and-Windows#202] opened 2020-08-31 05:38 UTC
## Expected Behavior
Request for appropriate "file" access permissions

## Actual Behavior
Only requests permissions for media and photos 

## Steps to Reproduce the Problem

  1. Call await CrossFilePicker.Current.PickFile( );
  2. Permissions should be requested 

## Specifications

  - NuGet package version: 2.1.44-beta
  - Platform(s): Android 10
![20200831_153459](https://user-images.githubusercontent.com/11971665/91686186-f6bb0300-eb9f-11ea-8cba-151e957fcd4b.png)

**Comment by jpveldtman** [comment] 2020-09-09 10:45
I handle the permissions myself using xamarin.essentials (CheckStatusAsync and RequestAsync),but noticed that with the CrossFilePicker.Current.PickFile on Huawei devices I get a access to the file is denied when reading the content. On Samsung it works fine. Seems that the MediaFile section is fine, it is just a problem with the FileData section. Selecting the image as the file does not show on the device but selecting the exact same image using PickPhotoAsync it works

**Comment by cmustd** [comment] 2020-09-26 02:10
I had this problem and was able to get the expected behavior by setting android:requestLegacyExternalStorage="true" on the application tag in the android manifest (see https://stackoverflow.com/questions/46911486/xamarin-system-unauthorizedaccessexception-access-to-the-path-is-denied). That setting is supposedly only allowed if targetting API <= 29, but I'm fine with that for now.

**Comment by jpveldtman** [comment] 2020-09-29 06:47
> I had this problem and was able to get the expected behavior by setting android:requestLegacyExternalStorage="true" on the application tag in the android manifest (see https://stackoverflow.com/questions/46911486/xamarin-system-unauthorizedaccessexception-access-to-the-path-is-denied). That setting is supposedly only allowed if targetting API <= 29, but I'm fine with that for now.

Thanks, I will give this a try... The weird thing is, I created a new project and then everything is working without doing anything weird. Copied the exact same code(Page, Code behind and viewmodel) to the existing project and there it is not working. The only thing i can think of is that a different package i added is working against it. But holding thumbs for your solution

**Comment by vividos** [comment] 2020-09-29 07:11
You could also check the Android target framework setting. I have mine in Android 11 and can't reproduce the error with that.

**Comment by dsvirdiau** [comment] 2020-09-29 07:16
setting android:requestLegacyExternalStorage="true"

This is not a proper solution. It does work after adding this but its only
temporary.

**Comment by jpveldtman** [comment] 2020-09-29 08:21
Thanks @vividos & @dsvirdiau 
I've tried targeting Android 11 and it was still not working on my current project. I've set the android:requestLegacyExternalStorage="true" together with Android 11, and now it is working. The weird thing is, on a new project Targeting Android 10 without the android:requestLegacyExternalStorage it is working but for some reason my project requires the android:requestLegacyExternalStorage setting
![image](https://user-images.githubusercontent.com/3882359/94531640-201d8c00-023d-11eb-8a20-d930d37555f6.png)

**Comment by jpveldtman** [comment] 2020-10-01 11:17
Hi @vividos & @dsvirdiau,
Ive changed initially my "Target Android version" to 11, once i've changed my "Compile using Android" to Android 11 it is working without the android:requestLegacyExternalStorage. Thanks for your help

**Comment by pedroyan** [comment] 2020-10-22 01:59
@jpveldtman @vividos I couldn't manage to fix find a fix for this.

Despite increasing my target version, ...
![image](https://user-images.githubusercontent.com/11574849/96809140-ab2f1380-13f0-11eb-8b0b-42aef1a13c83.png)

... setting the "Compile using Android Version" setting to Android 11, ...
![image](https://user-images.githubusercontent.com/11574849/96809417-34464a80-13f1-11eb-89c1-9f2e67c0d594.png)


... and clearing the solution (including manual delete of all `bin` and `obj` folders) before rebuilding it, the error still persists:

![image](https://user-images.githubusercontent.com/11574849/96809263-eb8e9180-13f0-11eb-8a0d-c31ea06a72cd.png)

I'm running my app on an API 29 device. Which Android version are your devices running on?

**Comment by vividos** [comment] 2020-10-22 10:44
I have used the same settings as you, and I've tested with a Pixel 3a device. I migrated to Xamarin.Essentials already, which also works fine.

**Comment by shahbaaz90** [comment] 2020-10-22 11:35
@vividos can you test on an android 10 or 9 device as well ? the pixel 3a might have android 11.. and im guessing this behaviour differs with the android version.

https://developer.android.com/training/data-storage/use-cases#handle-media-files

**Comment by vividos** [comment] 2020-10-22 18:21
I fear you have to test yourself, e.g. with an emulator. My pixel device is already on Android 11...

**Comment by jfversluis** [comment] 2020-10-22 18:40
Feel free to discuss any further, but I am closing all the things here in anticipation of archiving this project.

Closing this since this project will retire, please check out [Xamarin.Essentials](https://github.com/xamarin/Essentials/tree/main/Xamarin.Essentials/FilePicker) which now has a FilePicker based on this one.

**Closed as completed by jfversluis** 2020-10-22 18:40 UTC
