### ISSUE TITLE
InvalidOperationException("Only one operation can be active at a time");

### ISSUE THREAD

**Issue by VladislavAntonyuk** [jfversluis/FilePicker-Plugin-for-Xamarin-and-Windows#174] opened 2020-02-17 09:23 UTC
## Expected Behavior
Open dialog again

## Actual Behavior
App crashes

## Steps to Reproduce the Problem

  1. Open picker dialog
  1. Swipe down ( like close/cancel operation)
  1. Try to open dialog again

## Specifications

  - NuGet package version: latest
  - Platform: iOS 13 and higher

**Comment by karlingen** [comment] 2020-02-20 19:27
This is a known issue. 

>**InvalidOperationException "Only one operation can be active at a time"**
>This occurs when PickFile() is called multiple times and the task being awaited didn't return or throws an exception that wasn't caught. Be sure to catch any exceptions and handle them appropriately. See the example code above.

See https://github.com/jfversluis/FilePicker-Plugin-for-Xamarin-and-Windows#all-platforms

**Comment by vividos** [comment] 2020-02-28 19:08
Does the PickFile() call return? Maybe it has thrown an exception that you didn't catch? In this case .NET may forget about the exception altogether (and send an `UnobservedTaskException` event to notify you). Can you reproduce the error with the sample app?

**Comment by rihadavid** [comment] 2020-10-14 22:01
The problem with this is that even if you catch the exception, picker stops working until you restart the app.
When the exception happens, call this and then present the picker again, it will start working again:

```
try
{
       (Plugin.FilePicker.CrossFilePicker.Current as FilePickerImplementation)?.DocumentPicker_WasCancelled(null, null);
}
catch (Exception)
{
       //sender was null and won't be disposed, we can ignore that
}
```

**Comment by jfversluis** [comment] 2020-10-15 08:45
@rihadavid please have a look at Xamarin.Essentials, they have implemented a FilePicker partially based on this one. We will retire this library :) If there is still an issue, open it with them. Thanks!

**Comment by Edgaras91** [comment] 2020-10-22 13:28
@jfversluis Will do in near future, but currently, since it's only in preview, could we get a workaround? In the documentation mentioned above there was no example of how to handle this exception:


```
catch (Exception ex)
       {
            if (ex.Message == "Only one operation can be active at a time")
            {
                 //How to handle this - re initialize?
            }
        }
```

I could not understand @rihadavid "call this" solution. 
We are about to go in to production with our solution, and this is holding it up. 
Please advise.

**Comment by jfversluis** [comment] 2020-10-22 13:31
I understand your situation, but I think the "preview" is mostly a psychological barrier. Would it make you feel better if we would rush a fix in this library and release it? Or use a preview that is backed by a company like Microsoft?

I would suggest to just try the preview, see if that fixes it and works in all your other scenarios. If it does, I don't see why you can't use it.

**Comment by Edgaras91** [comment] 2020-10-22 14:06
> 
> 
> I understand your situation, but I think the "preview" is mostly a psychological barrier. Would it make you feel better if we would rush a fix in this library and release it? Or use a preview that is backed by a company like Microsoft?
> 
> I would suggest to just try the preview, see if that fixes it and works in all your other scenarios. If it does, I don't see why you can't use it.

Thanks, I wasn't expecting a fix, I was hoping there is a quick workaround mentioned in the documentation but not showing. 
I have tried Xamarin.Essentials FilePicker on 1.6.0-pre2 and it worked fine, just need to test a few more scenarios, so thanks!
I Will reply if it won't work on some scenarios as I suspect people will be coming here with the same issue.

**Comment by vividos** [comment] 2020-10-22 18:30
About the "Only one operation can be active at a time" exception... If you study the code of the implementation, you will see that this exception is only thrown when there is already a TaskCompletionSource active and was never cleared in the this.Handler call back.
By the way, did you leave the picker by swiping down the picker window? It seems another user stumbled over this and fixed it in #212...

**Comment by rihadavid** [comment] 2020-10-22 18:36
> I could not understand @rihadavid "call this" solution.

@Edgaras91 What did you not understand? Just add my code to your code instead of `//How to handle this - re initialize?` and call the method again (open the dialog again).

**Comment by jfversluis** [comment] 2020-10-22 18:37
Closing this since this project will retire, please check out [Xamarin.Essentials](https://github.com/xamarin/Essentials/tree/main/Xamarin.Essentials/FilePicker) which now has a FilePicker based on this one.

**Closed as completed by jfversluis** 2020-10-22 18:37 UTC

**Comment by jfversluis** [comment] 2020-10-22 18:39
Whoops sorry, wasn't meaning to interrupt an ongoing discussion. Was just cleaning up here :) feel free to continue, but don't expect a lot of effort on this project anymore.
