### ISSUE TITLE
IOS: Back and Cancel button on IOS aren't easily visible to click

### ISSUE THREAD

**Issue by muffadal53** [jfversluis/FilePicker-Plugin-for-Xamarin-and-Windows#141] opened 2019-07-23 10:12 UTC
When I add and use FilePicker plugin for IOS, the Back and Cancel navigation buttons look transparent (White Color) and not easily visible to click. It is the default theme of IOS and I haven't changed anything with respect to theme. The navigation buttons are of White Color and hence aren't easily visible to click. If we look at the default "Files" application in IOS these navigation buttons are usually of Blue background Color. So, they are easily visible for operation to end user. Do, I need to do something more to achieve the same behavior using FilePicker?

## Specifications

  - NuGet package version: 2.1.18
  - Platform(s): IOS 12.3.1

**Comment by vividos** [comment] 2019-07-27 19:19
Do you have a screenshot? When I tested the file picker on iOS, everything looked OK

**Comment by DevEddy** [comment] 2019-07-31 09:48
I have the same problem, there are just invisible but clickable.

![image](https://user-images.githubusercontent.com/7648336/62202157-0eb2c880-b389-11e9-9285-5277cd1bb484.png)

Edit: The button is clickable but not visible.

-- Eddy

**Comment by vividos** [comment] 2019-08-01 07:57
Could you reproduce it with the Sample app from this GitHub repository? Maybe it has to do with theming, the dialog applying some of the colors from the parent ViewController. I can only test on a real iOS device on next monday.

**Comment by muffadal53** [comment] 2019-08-01 08:31
> Could you reproduce it with the Sample app from this GitHub repository? Maybe it has to do with theming, the dialog applying some of the colors from the parent ViewController. I can only test on a real iOS device on next monday.

@vividos: Yes you are right. I think it is something related to the parent page in the application which is causing this problem. Today, When I tried using FilePciker in a Sample Xamarin Forms application and added FilePicker in MainPage.xaml.cs of the application on click of a button these navigation buttons are correctly visisble. Not sure how to fix this yet.

**Comment by DevEddy** [comment] 2019-08-02 12:44
> @vividos: Yes you are right. I think it is something related to the parent page in the application which is causing this problem. Today, When I tried using FilePciker in a Sample Xamarin Forms application and added FilePicker in MainPage.xaml.cs of the application on click of a button these navigation buttons are correctly visisble. Not sure how to fix this yet.

Were you able to find the reason for this? 
The [MediaPlugin](https://github.com/jamesmontemagno/MediaPlugin) works within the same page. 
I wonder which setting could it be?

-- Eddy

**Comment by muffadal53** [comment] 2019-08-05 08:42
> > @vividos: Yes you are right. I think it is something related to the parent page in the application which is causing this problem. Today, When I tried using FilePciker in a Sample Xamarin Forms application and added FilePicker in MainPage.xaml.cs of the application on click of a button these navigation buttons are correctly visisble. Not sure how to fix this yet.
> 
> Were you able to find the reason for this?
> The [MediaPlugin](https://github.com/jamesmontemagno/MediaPlugin) works within the same page.
> I wonder which setting could it be?
> 
> -- Eddy

Hi Eddy,

I haven't been able to find out the reason yet. Even, the "MediaPlugin" has the same behavior of transparent color when used in the application. But work's fine in a sample application. Need to investigate more.

Thanks.

**Comment by DevEddy** [comment] 2019-08-05 13:40
Hi @vividos,

for me, the MediaPlugin keeps my "style" of the app. But the FilePicker doesn't. Maybe there is the problem? 

Please let me know if you have something new. I am interested in a solution. Also I would try some cases if someone knows where I can start.

-- Eddy

**Comment by vividos** [comment] 2019-08-06 11:45
You can investigate the code yourself, it's in FiilePickerImplementation.ios.cs, and it uses UIDocumentPickerViewController internally. Maybe there can be passed a style. I'm short on time at the moment, sorry!

**Comment by DevEddy** [comment] 2019-08-08 14:43
Hi there,

I could find out what the problem is. 
Customize Text Color:             
```csharp
UINavigationBar.Appearance.TintColor = UIColor.Clear.FromHexString(hexColor);
```
But the background color seems not to work though it works in MediaPlugin.
```csharp
UINavigationBar.Appearance.BarTintColor = UIColor.Clear.FromHexString(hexColor);
```
So the workaround for me is just to set the text / item color before showing the Picker and then revert it to the "normal".

-- Eddy

**Comment by vividos** [comment] 2019-08-08 19:42
I don't remember the FilePicker plugin to set a bar tint color... so this is code from your app?

**Comment by DevEddy** [comment] 2019-08-08 21:16
Yeah it‘s from my app.

**Comment by muffadal53** [comment] 2019-08-09 09:12
> Yeah it‘s from my app.

@DevEddy: For me, the problem was setting of below 2 values in AppDelegate.cs.

UIBarButtonItem.Appearance.TintColor = UIColor.White;
UIToolbar.Appearance.BarTintColor = UIColor.LightGray;

After, removing this values from AppDelegate the navigation work's fine for both FilePicker and MediaPlugin, But the page title only work's fine for FilePicker not for MediaPlugin. The MediaPlugin still shows the page title in White color and not Black color as it should.

**Comment by DeerSteak** [comment] 2019-08-09 16:51
I don't want to remove the UIBarButtonItem.Appearance.TintColor from my app because the whole app uses NavigationPages with the nav bar set to white on dark blue as my theme. While it would be great if the file picker could use my theme, it is more important that the picker be usable. 

It should be as simple as reading the current tint color and then change it before presenting the viewController and then changing it back prior to dismissing it.

I can probably do that work (I'm mostly a beginner with Xamarin.iOS) but it'll be a bit before I have time. 

I wonder if the Media Picker uses UINavigationBar.Appearance.TintColor property instead of the UIBarButtonItem.Appearance.TintColor property.

**Comment by jfversluis** [comment] 2020-10-22 18:34
Closing this since this project will retire, please check out [Xamarin.Essentials](https://github.com/xamarin/Essentials/tree/main/Xamarin.Essentials/FilePicker) which now has a FilePicker based on this one.

**Closed as completed by jfversluis** 2020-10-22 18:34 UTC
