### ISSUE TITLE
File Picker won't pick file on iOS XCode 11.1

### ISSUE THREAD

**Issue by hanchhanch** [jfversluis/FilePicker-Plugin-for-Xamarin-and-Windows#156] opened 2019-10-20 07:47 UTC
It worked in past versions until I upgraded XCode to 11.1 and VS for Mac to 8.3.4

## Expected Behavior
File Picker is openned, 
the user selects a file
File Picker is closed and the file data is returned

## Actual Behavior
The File Picker is not closed after a user selects the file. Actually file selection doesn't seem to work at all. It is possible to rename the file, delete, etc. but not to select it.

## Steps to Reproduce the Problem
using Plugin.FilePicker;
using Plugin.FilePicker.Abstractions;
data = await CrossFilePicker.Current.PickFile();
if (data!=null)
{
}
  

## Specifications

  - NuGet package version: 2.1.34
  - Platform(s):
- Visual Studio for Mac 8.3.4 (Xamarin.iOS 13.4.0.2)
- XCode 11.1

**Comment by vividos** [comment] 2019-10-21 10:13
I guess this is on an iOS 13 device? Does it work on iOS 12?

**Comment by hanchhanch** [comment] 2019-10-21 15:13
Yes. Works on ios12.

**Comment by vividos** [comment] 2019-10-24 09:37
I just tested this with the FilePicker sample project on an iOS 13.1.3 and it works without problems. The file picker is presented as a page sheet, not as a new view controller, which is new in iOS 13. Can you reproduce the error with the sample project? If not, can you share more of your project code, best would be a compilable project. Thanks!

**Comment by dpozimski** [comment] 2020-01-15 08:35
Picker is not closing after file pick on my phone too. I use the newest iOS.

**Comment by mxstudios** [comment] 2020-04-01 19:40
Hi, Was this ever addressed? I am having same issue. Works fine on all versions except iOS 13.

**Comment by vividos** [comment] 2020-04-01 20:22
There was no code fix or something. If you can reproduce it, why to try to fix it? I don't have a Mac to debug this at the moment. We are happily accepting PRs!

**Comment by jfversluis** [comment] 2020-10-22 18:35
Closing this since this project will retire, please check out [Xamarin.Essentials](https://github.com/xamarin/Essentials/tree/main/Xamarin.Essentials/FilePicker) which now has a FilePicker based on this one.

**Closed as completed by jfversluis** 2020-10-22 18:35 UTC
