### ISSUE TITLE
[Feature Request] Option to pick multiple files (images and videos) from gallery

### ISSUE THREAD

**Issue by amirvenus** [jfversluis/FilePicker-Plugin-for-Xamarin-and-Windows#155] opened 2019-10-08 16:21 UTC
I am trying to use this plugin to get files that can be on the iCloud drive and/or the phone's gallery. 

I was wondering if we could have that feature please? 

Thanks!

**Comment by vividos** [comment] 2019-10-09 10:40
Is your request multiple selection? Then that ticket is a duplicate of #25. Picking images from the gallery could be managed with another Xamarin plugin, maybe Xamarin Essentials already has this feature.

**Comment by amirvenus** [comment] 2019-10-09 10:41
My request is a being able to select files from the gallery as well. (as well as selecting more than one).

In some cases, user might want to select a PDF file from iCloud Drive and/or image(s) from the Gallery in the same go.

**Comment by jfversluis** [comment] 2020-10-22 18:35
Closing this since this project will retire, please check out [Xamarin.Essentials](https://github.com/xamarin/Essentials/tree/main/Xamarin.Essentials/FilePicker) which now has a FilePicker based on this one.

**Closed as completed by jfversluis** 2020-10-22 18:35 UTC
Labels: enhancement
